### PR TITLE
Enhancement/lime survey 63 add events

### LINKED ISSUE #63: [LimeSurveyUploader] Add Events
- [x] onError(string error, string detail)
- [x] onWarning(string warning, string detail)
- [x] onStartLogin() called when the login process starts
- [x] onLoggedIn() called when the user successfully logged in (else onError should be called)
- [x] onStartLoadQuestions() called when the questions are loaded
- [x] onQuestionsLoaded() called once the questions have been received and setup (else onError should be called)
- [x] onStartSubmission
- [x] onSubmissionFinished

### LINKED ISSUE #66: Lime Survey Issues
MC answer option order is wrong:
image
image

MC int codes:
Next button only active if all boxes ticked
image

### PR DESCRIPTION
**Pull request by sandra-bre**
closes #63 
closes #66

### CODE REVIEW

**Comment by codecreativity** [comment]
Found some issues, listed them in #66, should probably fix this before merge

**Comment by sandra-bre** [comment]
closes #66 as well

**Comment by codecreativity** [comment]
I think the way the events are setup at multiple locations with identical names is not ideal. We should probably have one location where the events are defined and managed. If it is necessary to have events of the same type created in different classes we should at least name them differently to be able to tell them apart.

The mandatory requirements seem to be checked at multiple locations. We should merge that into one place as well.

**Comment by codecreativity** [comment]
I found some issues with the gitignore as well, I will address this first

**Comment by codecreativity** [comment]
We should merge #67 first, then update this with dev, then do additional stuff here

**Review by codecreativity — APPROVED** [review]
Approved because changes needed quickly elsewhere. Potential issues need to be fixed later.

**Pull request merged**
