### PR TITLE
Feature/vr interaction

### LINKED ISSUE #35: [VR Interaction] Setup
Create a basic VR Interaction Plugin containing:
- [x] SteamVR + Oculus Integration
- [x] Player Prefab
- [x] Teleportation
- [x] Button
- [x] Switch
- [x] Slider
- [x] Snap Zones

**Testing if it works on:**
- [x] Oculus Quest + Oculus Quest 2
- [x] HTC Vive

- [x] **Test importing the plugin**

### PR DESCRIPTION
**Pull request by sandra-bre**

### CODE REVIEW

**Comment by michaelholly** [comment]
Can we move the Oculus Integration Package into the 3Party folder?
BTW: The Oculus Android and Oculus Desktop Package is deprecated and will be removed in Unity 2020. 
In this case, we should upgrade to the Oculus XR Plugin. Can you check if this is working with the SteamVR plugin too?
Maybe we can also add this dependence into the package dependence list in the package.json file.

**Comment by michaelholly** [comment]
Can you please update the SteamVR plugin from 2.5 to 2.7

**Comment by michaelholly** [comment]
@package.json
please change the name = "com.gamelabgraz.vrinteraction", the unity version = "2019.4", author = "Game Lab Graz" and update the dependencies if possible

**Comment by michaelholly** [comment]
Please change also the namespace of your scripts to GameLabGraz.VRInteraction

**Comment by sandra-bre** [comment]
please check again :)

**Review by michaelholly — DISMISSED** [review]
Please move or remove the Oculus Integration Package and replace it with the Oculus XR Plugin for the Unity 2020 Upgrade in your next PR.

**Pull request merged**
